name: GitHub Metrics Actions
on:
  schedule:
    - cron: "0 0-23/12 * * *"
  push:
    branches: 
      - master
      - main
  workflow_dispatch:
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal Metrics
        if: ${{ success() || failure() }}
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_isocalendar: yes
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%
          
      - name: Personal Metrics (Additional)
        if: ${{ success() || failure() }}
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c
          plugin_languages_skipped: Harry-Yep
          plugin_languages_details: bytes-size, percentage
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          config_order: base.header, languages, pagespeed, habits, stargazers, stars
          config_padding: 6%, 10%
          
      - name: Personal Metrics (Anilist)
        if: ${{ success() || failure() }}
        uses: Harry-Yep/metrics@master
        with:
          filename: img/metrics/metrics.plugin.personal.anilist.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          config_padding: 6%, 10%